const RUTAS = {
    INICIO: 'index.html',
    ADMIN: "paginas/admin.html",            
    CARRITO: 'paginas/carrito.html',
    CATALOGO: 'paginas/catalogo.html',
    CHECKOUT: 'paginas/checkout.html',    
    COLCHONES: 'paginas/colchones.html',
    COMEDORES: 'paginas/comedores.html',
    CONTACTO: 'paginas/contacto.html',
    DORMITORIOS: 'paginas/dormitorios.html',
    FACTURAS: 'paginas/facturas.html',
    GARANTIA: 'paginas/garantia.html',
    LINEABLANCA: 'paginas/lineaBlanca.html',
    NOSOTROS: 'paginas/nosotros.html',
    OFERTAS: 'paginas/ofertas.html',
    PERFIL: 'paginas/perfil.html',
    POLITICAS: 'paginas/politicas.html',
    PREGUNTAS: 'paginas/preguntas.html',
    PROVEEDORES: 'paginas/proveedores.html',
    ROPEROS: 'paginas/roperos.html',
    SALAS: 'paginas/salas.html',
};