//modelo JSON 
export const products = [
//PROUCTOS DE CABECERAS EN LA LISTA
  {
    "id": 196,
    "sku": "CAB-KING-001",
    "categoria": "Dormitorios",
    "subcategoria": "cabecera",
    "nombre": "CABECERA ACOLCHONADA KING SIZE",
    "descripcion": "Cabecera acolchada tamaño king size, tapizada en tela de alta calidad, ideal para dormitorios modernos.",
    "precio": 2000.0,
    "moneda": "MXN",
    "materiales": "Madera MDF, espuma, tela premium",
    "dimensiones": "200cm x 10cm x 120cm",
    "img": "https://m.media-amazon.com/images/I/81mknSwKTUL.jpg",
    "stock": 30,
    "oferta": 0,
    "porcentajeOferta": 0
  },
  {
    "id": 197,
    "sku": "CAB-MAT-002",
    "categoria": "Dormitorios",
    "subcategoria": "cabecera",
    "nombre": "CABECERA ACOLCHONADA MATRIMONEAL",
    "descripcion": "Cabecera acolchada matrimonial, con diseño elegante y resistente, perfecta para recámaras modernas.",
    "precio": 2000.0,
    "moneda": "MXN",
    "materiales": "Madera MDF, espuma, tela premium",
    "dimensiones": "160cm x 10cm x 110cm",
    "img": "https://makali.mx/wp-content/uploads/2017/11/cabecera-makali2.jpg",
    "stock": 30,
    "oferta": 0,
    "porcentajeOferta": 0
  },
  {
    "id": 198,
    "sku": "CAB-IND-003",
    "categoria": "Dormitorios",
    "subcategoria": "cabecera",
    "nombre": "CABECERA ACOLCHONADA INDIVIDUAL",
    "descripcion": "Cabecera acolchada individual, con diseño compacto y cómodo, ideal para camas sencillas.",
    "precio": 2000.0,
    "moneda": "MXN",
    "materiales": "Madera MDF, espuma, tela premium",
    "dimensiones": "100cm x 10cm x 90cm",
    "img": "https://makali.mx/wp-content/uploads/2016/08/cabecera-de-cama-con-base-y-piecera-min.jpg",
    "stock": 20,
    "oferta": 0,
    "porcentajeOferta": 0
  },
  //AÑADI 3 MAS DE LA SUBCATEGORIA CABECERA
  {
  "id": 199,
  "sku": "CAB-MOD-004",
  "categoria": "Dormitorios",
  "subcategoria": "cabecera",
  "nombre": "CABECERA MODERNA CAPITONADA QUEEN SIZE",
  "descripcion": "Cabecera capitonada tamaño queen, con elegantes botones y tapizado en lino gris. Ideal para dar un toque sofisticado a tu dormitorio.",
  "precio": 2400.0,
  "moneda": "MXN",
  "materiales": "Madera sólida, espuma de alta densidad, lino gris",
  "dimensiones": "180cm x 12cm x 115cm",
  "img": "https://m.media-amazon.com/images/I/71y0gPL3RGL._AC_SL1500_.jpg",
  "stock": 25,
  "oferta": 0,
  "porcentajeOferta": 0
},
{
  "id": 200,
  "sku": "CAB-RUS-005",
  "categoria": "Dormitorios",
  "subcategoria": "cabecera",
  "nombre": "CABECERA RÚSTICA DE MADERA NATURAL",
  "descripcion": "Cabecera artesanal elaborada con madera natural barnizada, de estilo rústico y duradero. Ideal para recámaras con decoración campestre.",
  "precio": 2700.0,
  "moneda": "MXN",
  "materiales": "Madera de pino maciza, barniz natural",
  "dimensiones": "190cm x 8cm x 120cm",
  "img": "https://m.media-amazon.com/images/I/81SrG5UnsaL._AC_SL1500_.jpg",
  "stock": 15,
  "oferta": 0,
  "porcentajeOferta": 0
},
{
  "id": 201,
  "sku": "CAB-TAP-006",
  "categoria": "Dormitorios",
  "subcategoria": "cabecera",
  "nombre": "CABECERA TAPIZADA CON LUZ LED",
  "descripcion": "Cabecera tapizada con luz LED integrada y botones decorativos, perfecta para crear un ambiente moderno y funcional.",
  "precio": 3200.0,
  "moneda": "MXN",
  "materiales": "Madera MDF, espuma, tela sintética, luces LED",
  "dimensiones": "200cm x 12cm x 125cm",
  "img": "https://m.media-amazon.com/images/I/71h8pP4iDxL._AC_SL1500_.jpg",
  "stock": 10,
  "oferta": 0,
  "porcentajeOferta": 0
},

  //PRODUCTOS DE BASE EN LA LISTA
  {
    "id": 172,
    "sku": "BOX-ALEX-IND-004",
    "categoria": "Dormitorios",
    "subcategoria": "base",
    "nombre": "BOX ALEX INDIVIDUAL",
    "descripcion": "Base individual para cama tipo box, artesanal y resistente, con soporte firme para colchón estándar.",
    "precio": 3000.0,
    "moneda": "MXN",
    "materiales": "Madera MDF, tapizado en tela",
    "dimensiones": "100cm x 190cm x 30cm",
    "img": "https://m.media-amazon.com/images/I/71KQgp86AKL._AC_SL1500_.jpg",
    "stock": 20,
    "oferta": 0,
    "porcentajeOferta": 0
  },
  {
    "id": 173,
    "sku": "BOX-ALEX-MAT-005",
    "categoria": "Dormitorios",
    "subcategoria": "base",
    "nombre": "BOX ALEX MATRIMONEAL SIN CAJONES",
    "descripcion": "Base matrimonial tipo box, sin cajones, artesanal y resistente, ideal para colchones matrimoniales.",
    "precio": 3000.0,
    "moneda": "MXN",
    "materiales": "Madera MDF, tapizado en tela",
    "dimensiones": "160cm x 200cm x 30cm",
    "img": "https://resources.sears.com.mx/medios-plazavip/mkt/61fac3a1c7858_plopng.jpg?scale=500&qlty=75",
    "stock": 20,
    "oferta": 0,
    "porcentajeOferta": 0
  },
  {
    "id": 207,
    "sku": "CAJ-BUC-006",
    "categoria": "Dormitorios",
    "subcategoria": "base",
    "nombre": "CAJONERA BUCIO",
    "descripcion": "Cajonera de madera artesanal, con varios compartimentos, perfecta para almacenamiento en recámaras.",
    "precio": 3000.0,
    "moneda": "MXN",
    "materiales": "Madera maciza, barniz natural",
    "dimensiones": "80cm x 40cm x 90cm",
    "img": "https://d38qrl83hrqn1t.cloudfront.net/media/catalog/product/cache/e5313a059d82e47a0dd0c73b13afb6be/1/-/1-_0001_base-d_1.jpg",
    "stock": 20,
    "oferta":0,
    "porcentajeOferta": 0
  },
//AÑADI 3 PRODUCTOS MAS DE LA SUBCATEGORIA BASE
{
  "id": 208,
  "sku": "BOX-LUX-KING-007",
  "categoria": "Dormitorios",
  "subcategoria": "base",
  "nombre": "BASE BOX LUXURY KING SIZE CON CAJONES",
  "descripcion": "Base tipo box tamaño king con cajones laterales. Fabricada artesanalmente en madera reforzada y tapizada en tela gris premium.",
  "precio": 4500.0,
  "moneda": "MXN",
  "materiales": "Madera maciza, tela gris, herrajes metálicos",
  "dimensiones": "200cm x 200cm x 35cm",
  "img": "https://m.media-amazon.com/images/I/71DM4z1vQtL._AC_SL1500_.jpg",
  "stock": 10,
  "oferta": 1,
  "porcentajeOferta": 15
},
{
  "id": 209,
  "sku": "BOX-MOD-QUEEN-008",
  "categoria": "Dormitorios",
  "subcategoria": "base",
  "nombre": "BASE BOX MODERNA QUEEN SIZE",
  "descripcion": "Base moderna tipo box tamaño queen, tapizada en lino color beige con estructura firme y diseño minimalista.",
  "precio": 3800.0,
  "moneda": "MXN",
  "materiales": "Madera MDF, lino beige, espuma densa",
  "dimensiones": "160cm x 200cm x 32cm",
  "img": "https://m.media-amazon.com/images/I/81lbnb5tRzL._AC_SL1500_.jpg",
  "stock": 15,
  "oferta": 0,
  "porcentajeOferta": 0
},
{
  "id": 210,
  "sku": "BOX-ECO-MAT-009",
  "categoria": "Dormitorios",
  "subcategoria": "base",
  "nombre": "BASE ECOLÓGICA MATRIMONIAL DE MADERA NATURAL",
  "descripcion": "Base matrimonial ecológica elaborada en madera reciclada con acabado natural. Ideal para un estilo sustentable y elegante.",
  "precio": 3400.0,
  "moneda": "MXN",
  "materiales": "Madera reciclada tratada, barniz ecológico",
  "dimensiones": "160cm x 200cm x 30cm",
  "img": "https://m.media-amazon.com/images/I/81XwNFWN5bL._AC_SL1500_.jpg",
  "stock": 12,
  "oferta": 1,
  "porcentajeOferta": 10
},
  //PRODUCTOS DE RECAMARAS EN LA LISTA
  {
    "id": 1332,
    "sku": "IMP-EMI-001",
    "categoria": "Dormitorios",
    "subcategoria": "recamaras",
    "nombre": "RECAMARA IMPERIAL MOD: EMILY",
    "descripcion": "Recámara de estilo clásico con acabado en madera noble, incluye cabecera y base matrimonial.",
    "precio": 24700.0,
    "moneda": "MXN",
    "materiales": "Madera maciza, MDF, barniz natural",
    "dimensiones": "200cm x 180cm x 100cm",
    "img": "https://ivannamuebles.com/wp-content/uploads/2024/02/emily_a.webp",
    "stock": 2,
    "oferta": 0,
    "porcentajeOferta": 0
  },
  {
    "id": 1335,
    "sku": "IMP-DUB-002",
    "categoria": "Dormitorios",
    "subcategoria": "recamaras",
    "nombre": "RECAMARA IMPERIAL MOD: DUBAI",
    "descripcion": "Recámara moderna con detalles elegantes en madera y herrajes metálicos, incluye base y cabecera king size.",
    "precio": 18200.0,
    "moneda": "MXN",
    "materiales": "Madera MDF, tapizado en tela, metal cromado",
    "dimensiones": "210cm x 190cm x 105cm",
    "img": "https://www.mueblestroncoso.com.mx/8754-home_default/recamara-praga.jpg",
    "stock": 2,
    "oferta": 0,
    "porcentajeOferta": 0
  },
  {
    "id": 1350,
    "sku": "IVA-ALE-003",
    "categoria": "Dormitorios",
    "subcategoria": "recamaras",
    "nombre": "RECAMARA IVANNA MOD: ALEJANDRINA",
    "descripcion": "Recámara de diseño contemporáneo con cabecera acolchada y base matrimonial, ideal para espacios elegantes.",
    "precio": 16200.0,
    "moneda": "MXN",
    "materiales": "Madera MDF, tapizado en cuero sintético",
    "dimensiones": "200cm x 180cm x 95cm",
    "img": "https://static.wixstatic.com/media/26742d_d8ded878ae9e4da98bc63411c24b0ef4~mv2.jpg/v1/fill/w_980,h_635,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/26742d_d8ded878ae9e4da98bc63411c24b0ef4~mv2.jpg",
    "stock": 3,
    "oferta": 0,
    "porcentajeOferta": 0
  },
  {
    "id": 1359,
    "sku": "IVA-HOL-004",
    "categoria": "Dormitorios",
    "subcategoria": "recamaras",
    "nombre": "RECAMARA IVANNA MOD: HOLLY",
    "descripcion": "Recámara moderna con cabecera alta, diseño minimalista y base resistente, perfecta para dormitorios amplios.",
    "precio": 19000.0,
    "moneda": "MXN",
    "materiales": "Madera MDF, tapizado en tela premium",
    "dimensiones": "205cm x 185cm x 100cm",
    "img": "https://ivannamuebles.com/wp-content/uploads/2024/02/itzel_holly_a-1536x905.webp",
    "stock": 2,
    "oferta": 0,
    "porcentajeOferta": 0
  },
  {
    "id": 1365,
    "sku": "SF-ESPE-005",
    "categoria": "Dormitorios",
    "subcategoria": "recamaras",
    "nombre": "RECAMARA SAN FELIPE MOD: ESPEJO ECONOMICA",
    "descripcion": "Recámara económica con cabecera con espejo incorporado, ideal para habitaciones funcionales y modernas.",
    "precio": 13000.0,
    "moneda": "MXN",
    "materiales": "Madera laminada, espejo de seguridad",
    "dimensiones": "195cm x 175cm x 90cm",
    "img": "https://www.mueblestroncoso.com.mx/8656-home_default/recamara-yakaty-5-pzs.jpg",
    "stock": 6,
    "oferta": 0,
    "porcentajeOferta": 0
  }
];
