export const products = [
    // --- Modulares de 4 Piezas --- 
    // (Selección de salas esquineras y modulares de tu lista, asumidas como 4 piezas)
    {
        id: 301, 
        sku: 'SAL-MAN-NATYESQ',
        categoria: 'Salas',
        subcategoria: 'Modulares de 4 piezas',
        nombre: 'SALA MANIA MOD: NATY ESQUINERA', 
        descripcion: 'Sala esquinera versátil y moderna, ideal para optimizar espacios pequeños y medianos. Tapizada en tela duradera y de fácil limpieza.', 
        precio: 7200.00, 
        moneda: 'MXN', 
        materiales: ['Tela', 'Madera de pino', 'Espuma de alta densidad'], 
        dimensiones: { alto: 85, ancho: 220, profundidad: 150, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/mania_naty_esquinera.jpg', 
        stock: 18,
        oferta: 0,
        porcentajeOferta: 0

    },
    {
        id: 302, 
        sku: 'SAL-ORT-DORESQ',
        categoria: 'Salas',
        subcategoria: 'Modulares de 4 piezas',
        nombre: 'SALA ORTEGA MOD: DORIS ESQUINERA', 
        descripcion: 'Un diseño elegante que combina confort y estilo. Cojines de respaldo cómodos y una estructura robusta para el uso diario.', 
        precio: 10000.00, 
        moneda: 'MXN', 
        materiales: ['Lino sintético', 'Madera', 'Patas metálicas'], 
        dimensiones: { alto: 90, ancho: 240, profundidad: 160, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/ortega_doris_esquinera.jpg', 
        stock: 11,
        oferta: 0,
        porcentajeOferta: 0

    },
    {
        id: 303, 
        sku: 'SAL-ORT-JASHESQ',
        categoria: 'Salas',
        subcategoria: 'Modulares de 4 piezas',
        nombre: 'SALA ORTEGA MOD: JASHUA ESQUINERA', 
        descripcion: 'Perfecta para reuniones familiares, con un diseño contemporáneo y un chaise longue para mayor comodidad.', 
        precio: 9000.00, 
        moneda: 'MXN', 
        materiales: ['Microfibra', 'Madera de pino estufada', 'Espuma'], 
        dimensiones: { alto: 88, ancho: 230, profundidad: 155, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/ortega_jashua_esquinera.jpg', 
        stock: 14,
        oferta: 0,
        porcentajeOferta: 0
    },
    {
        id: 304, 
        sku: 'SAL-ORT-MALESQ',
        categoria: 'Salas',
        subcategoria: 'Modulares de 4 piezas',
        nombre: 'SALA ORTEGA MOD: MALAGA ESQUINERA', 
        descripcion: 'Diseño funcional y acogedor, la sala Málaga es ideal para crear un ambiente cálido en tu hogar.', 
        precio: 10100.00, 
        moneda: 'MXN', 
        materiales: ['Tela tipo lino', 'Madera', 'Resorte'], 
        dimensiones: { alto: 85, ancho: 250, profundidad: 160, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/ortega_malaga_esquinera.jpg', 
        stock: 16,
        oferta: 0,
        porcentajeOferta: 0
    },
    {
        id: 305, 
        sku: 'SAL-RUI-ANTESQ',
        categoria: 'Salas',
        subcategoria: 'Modulares de 4 piezas',
        nombre: 'SALA RUIZ MOD: ANTONY ESQUINERA', 
        descripcion: 'Líneas limpias y un estilo minimalista definen a la sala Antony, una pieza central para una decoración moderna.', 
        precio: 10800.00, 
        moneda: 'MXN', 
        materiales: ['Piel sintética', 'Madera de pino', 'Patas cromadas'], 
        dimensiones: { alto: 82, ancho: 245, profundidad: 150, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/ruiz_antony_esquinera.jpg', 
        stock: 9,
        oferta: 0,
        porcentajeOferta: 0
    },
    {
        id: 306, 
        sku: 'SAL-ORT-ROMESQ',
        categoria: 'Salas',
        subcategoria: 'Modulares de 4 piezas',
        nombre: 'SALA ORTEGA MOD: ROMA ESQUINERA', 
        descripcion: 'Inspiración clásica con un toque moderno. Amplia y confortable, perfecta para largas tardes de relax.', 
        precio: 12100.00, 
        moneda: 'MXN', 
        materiales: ['Chenille', 'Estructura de madera', 'Espuma viscoelástica'], 
        dimensiones: { alto: 92, ancho: 260, profundidad: 170, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/ortega_roma_esquinera.jpg', 
        stock: 13,
        oferta: 0,
        porcentajeOferta: 0
    },
    {
        id: 307, 
        sku: 'SAL-VIC-DIXTRE',
        categoria: 'Salas',
        subcategoria: 'Modulares de 4 piezas',
        nombre: 'SALA VICSA DIXON TREVISO', 
        descripcion: 'Un conjunto modular que destaca por su diseño único y la calidad de sus materiales. Aporta sofisticación a cualquier espacio.', 
        precio: 12900.00, 
        moneda: 'MXN', 
        materiales: ['Tela Treviso', 'Madera sólida', 'Patas de diseño'], 
        dimensiones: { alto: 87, ancho: 255, profundidad: 165, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/vicsa_dixon_treviso.jpg', 
        stock: 10,
        oferta: 0,
        porcentajeOferta: 0
    },

    // --- Modulares de 5 Piezas ---
    // (Selección de salas 3-2-1 y otras de gran tamaño de tu lista, asumidas como 5 piezas)
    {
        id: 308, 
        sku: 'SAL-MAN-NATY321',
        categoria: 'Salas',
        subcategoria: 'Modulares de 5 piezas',
        nombre: 'SALA MANIA MOD NATY 3-2-1', 
        descripcion: 'Conjunto completo de 3 piezas (Sofá, Love Seat e Individual). Un diseño clásico que nunca pasa de moda, ideal para familias.', 
        precio: 10800.00, 
        moneda: 'MXN', 
        materiales: ['Tela de alto tráfico', 'Madera sólida', 'Espuma de alta densidad'], 
        dimensiones: { alto: 90, ancho: 350, profundidad: 90, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/mania_naty_321.jpg', 
        stock: 15,
        oferta: 0,
        porcentajeOferta: 0
    },
    {
        id: 309, 
        sku: 'SAL-ORT-AID321',
        categoria: 'Salas',
        subcategoria: 'Modulares de 5 piezas',
        nombre: 'SALA ORTEGA MOD: AIDEE 321', 
        descripcion: 'Elegancia y confort en un set completo. Cojines decorativos incluidos para un look completo y acogedor.', 
        precio: 17000.00, 
        moneda: 'MXN', 
        materiales: ['Lino', 'Madera de roble', 'Relleno de pluma sintética'], 
        dimensiones: { alto: 88, ancho: 360, profundidad: 95, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/ortega_aidee_321.jpg', 
        stock: 8,
        oferta: 0,
        porcentajeOferta: 0
    },
    {
        id: 310, 
        sku: 'SAL-ORT-DAZ321',
        categoria: 'Salas',
        subcategoria: 'Modulares de 5 piezas',
        nombre: 'SALA ORTEGA MOD: DAZA 321', 
        descripcion: 'Diseño robusto y confortable, tapizado en materiales resistentes, ideal para el uso continuo y familiar.', 
        precio: 16200.00, 
        moneda: 'MXN', 
        materiales: ['Tela', 'Madera de pino', 'Patas de metal'], 
        dimensiones: { alto: 92, ancho: 340, profundidad: 92, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/ortega_daza_321.jpg', 
        stock: 10,
        oferta: 0,
        porcentajeOferta: 0
    },
    {
        id: 311, 
        sku: 'SAL-REN-GIN321',
        categoria: 'Salas',
        subcategoria: 'Modulares de 5 piezas',
        nombre: 'SALA RENE MOD: GINA 3-2-1', 
        descripcion: 'Un conjunto que combina piezas para ofrecer máxima capacidad. Estilo contemporáneo que se adapta a diversas decoraciones.', 
        precio: 17400.00, 
        moneda: 'MXN', 
        materiales: ['Terciopelo', 'Madera estufada', 'Espuma'], 
        dimensiones: { alto: 85, ancho: 370, profundidad: 100, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/rene_gina_321.jpg', 
        stock: 9,
        oferta: 0,
        porcentajeOferta: 0
    },
    {
        id: 312, 
        sku: 'SAL-ORT-RAC321',
        categoria: 'Salas',
        subcategoria: 'Modulares de 5 piezas',
        nombre: 'SALA ORTEGA MOD: RACHEL 321', 
        descripcion: 'Confort superior y un diseño atemporal. El set Rachel es una inversión en comodidad para tu hogar.', 
        precio: 17400.00, 
        moneda: 'MXN', 
        materiales: ['Piel sintética', 'Madera de pino', 'Metal cromado'], 
        dimensiones: { alto: 90, ancho: 355, profundidad: 98, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/ortega_rachel_321.jpg', 
        stock: 12,
        oferta: 0,
        porcentajeOferta: 0
    },
    {
        id: 313, 
        sku: 'SAL-FLO-GRECIA',
        categoria: 'Salas',
        subcategoria: 'Modulares de 5 piezas',
        nombre: 'SALA FLORIDA MOD: GRECIA', 
        descripcion: 'Un modelo de lujo con amplios asientos y acabados de primera calidad, para quienes buscan distinción y confort.', 
        precio: 24200.00, 
        moneda: 'MXN', 
        materiales: ['Piel genuina', 'Madera de cedro', 'Espuma de memoria'], 
        dimensiones: { alto: 95, ancho: 380, profundidad: 110, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/florida_grecia.jpg', 
        stock: 6,
        oferta: 0,
        porcentajeOferta: 0
    },
    {
        id: 314, 
        sku: 'SAL-ORT-KANON',
        categoria: 'Salas',
        subcategoria: 'Modulares de 5 piezas',
        nombre: 'SALA ORTEGA KANON', 
        descripcion: 'Imponente y sofisticada, la sala Kanon es el centro de todas las miradas. Máximo confort y diseño de vanguardia.', 
        precio: 26300.00, 
        moneda: 'MXN', 
        materiales: ['Lino grueso', 'Madera sólida', 'Resortes de acero'], 
        dimensiones: { alto: 91, ancho: 400, profundidad: 105, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/ortega_kanon.jpg', 
        stock: 5,
        oferta: 0,
        porcentajeOferta: 0
    },

    // --- Sofacamas ---
    // (Los 3 de tu lista + 4 creados para llegar a 7)
    {
        id: 315, 
        sku: 'SOF-MAN-NINEL',
        categoria: 'Salas',
        subcategoria: 'Sofacamas',
        nombre: 'SOFA CAMA MANIA MOD: NINEL', 
        descripcion: 'Funcional y moderno sofá cama tipo futón, se convierte en cama matrimonial en segundos. Ideal para visitas.', 
        precio: 8100.00, 
        moneda: 'MXN', 
        materiales: ['Tela tipo lino', 'Madera de pino', 'Patas de madera'], 
        dimensiones: { alto: 80, ancho: 190, profundidad: 90, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/sofacama_mania_ninel.jpg', 
        stock: 25,
        oferta: 0,
        porcentajeOferta: 0
    },
    {
        id: 316, 
        sku: 'SOF-ORT-MAT',
        categoria: 'Salas',
        subcategoria: 'Sofacamas',
        nombre: 'SOFA CAMA ORTEGA MATRIMONEAL', 
        descripcion: 'Un sofá cama práctico y cómodo, con un sistema de apertura sencillo. Perfecto para cualquier habitación.', 
        precio: 6100.00, 
        moneda: 'MXN', 
        materiales: ['Microfibra', 'Estructura metálica', 'Espuma'], 
        dimensiones: { alto: 78, ancho: 180, profundidad: 85, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/sofacama_ortega_mat.jpg', 
        stock: 30,
        oferta: 0,
        porcentajeOferta: 0
    },
    {
        id: 317, 
        sku: 'SOF-VAL-LUNA',
        categoria: 'Salas',
        subcategoria: 'Sofacamas',
        nombre: 'SOFA CAMA VALMART MOD: LUNA', 
        descripcion: 'Diseño juvenil y fresco, el sofá cama Luna aporta un toque de color y funcionalidad a tu espacio.', 
        precio: 7300.00, 
        moneda: 'MXN', 
        materiales: ['Tela', 'Metal', 'Relleno de algodón y espuma'], 
        dimensiones: { alto: 75, ancho: 185, profundidad: 88, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/sofacama_valmart_luna.jpg', 
        stock: 22,
        oferta: 0,
        porcentajeOferta: 0
    },
    {
        id: 318, 
        sku: 'SOF-GEN-ITALO',
        categoria: 'Salas',
        subcategoria: 'Sofacamas',
        nombre: 'SOFA CAMA MODELO ITALIANO', 
        descripcion: 'Mecanismo de apertura italiano que despliega un colchón real sin quitar cojines. Máximo confort.', 
        precio: 14500.00, 
        moneda: 'MXN', 
        materiales: ['Piel sintética', 'Mecanismo de acero', 'Colchón de espuma'], 
        dimensiones: { alto: 95, ancho: 200, profundidad: 100, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/sofacama_generico_italiano.jpg', 
        stock: 14,
        oferta: 0,
        porcentajeOferta: 0
    },
    {
        id: 319, 
        sku: 'SOF-GEN-CHAISE',
        categoria: 'Salas',
        subcategoria: 'Sofacamas',
        nombre: 'SOFA CAMA CON CHAISE LONGE', 
        descripcion: 'Sofá cama versátil que incluye un chaise longe para mayor comodidad diaria y espacio de almacenamiento.', 
        precio: 12999.00, 
        moneda: 'MXN', 
        materiales: ['Chenille', 'Madera de pino', 'Espuma'], 
        dimensiones: { alto: 88, ancho: 230, profundidad: 150, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/sofacama_generico_chaise.jpg', 
        stock: 18,
        oferta: 0,
        porcentajeOferta: 0
    },
    {
        id: 320, 
        sku: 'SOF-GEN-LOVE',
        categoria: 'Salas',
        subcategoria: 'Sofacamas',
        nombre: 'SOFA CAMA TIPO LOVESEAT', 
        descripcion: 'Perfecto para espacios reducidos, este loveseat se convierte en una cama individual para un huésped.', 
        precio: 7899.00, 
        moneda: 'MXN', 
        materiales: ['Tela', 'Madera', 'Metal'], 
        dimensiones: { alto: 82, ancho: 150, profundidad: 92, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/sofacama_generico_loveseat.jpg', 
        stock: 28,
        oferta: 0,
        porcentajeOferta: 0
    },
    {
        id: 321, 
        sku: 'SOF-GEN-VINTAGE',
        categoria: 'Salas',
        subcategoria: 'Sofacamas',
        nombre: 'SOFA CAMA ESTILO VINTAGE', 
        descripcion: 'Estilo retro con patas de madera anguladas y tapizado en tela texturizada. Una pieza de diseño funcional.', 
        precio: 9500.00, 
        moneda: 'MXN', 
        materiales: ['Tela texturizada', 'Madera sólida', 'Espuma de alta densidad'], 
        dimensiones: { alto: 84, ancho: 215, profundidad: 89, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/sofacama_generico_vintage.jpg', 
        stock: 16,
        oferta: 0,
        porcentajeOferta: 0
    },

    // --- Reclinables ---
    // (Los 2 de tu lista + 5 creados para llegar a 7)
    {
        id: 322, 
        sku: 'SAL-KOM-REPO',
        categoria: 'Salas',
        subcategoria: 'Reclinables',
        nombre: 'SALA KOMFORT REPOSET', 
        descripcion: 'Un reposet individual sumamente cómodo, con mecanismo de reclinación manual y reposapiés acolchado.', 
        precio: 5100.00, 
        moneda: 'MXN', 
        materiales: ['Microfibra', 'Estructura de metal y madera', 'Acolchado de espuma'], 
        dimensiones: { alto: 105, ancho: 90, profundidad: 95, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/komfort_reposet.jpg', 
        stock: 20,
        oferta: 0,
        porcentajeOferta: 0
    },
    {
        id: 323, 
        sku: 'SAL-ORT-ATE2REC',
        categoria: 'Salas',
        subcategoria: 'Reclinables',
        nombre: 'SALA ORTEGA MOD: ATENAS 2 RECLINABLES', 
        descripcion: 'Sofá de 3 plazas con dos asientos reclinables en los extremos. Confort de lujo para tu sala de estar o cine en casa.', 
        precio: 27600.00, 
        moneda: 'MXN', 
        materiales: ['Piel sintética', 'Motor eléctrico', 'Acero', 'Puerto USB'], 
        dimensiones: { alto: 102, ancho: 220, profundidad: 100, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/ortega_atenas_2rec.jpg', 
        stock: 15,
        oferta: 0,
        porcentajeOferta: 0

    },
    {
        id: 324, 
        sku: 'REC-GEN-LOVECON',
        categoria: 'Salas',
        subcategoria: 'Reclinables',
        nombre: 'SOFA RECLINABLE 2 PLAZAS CON CONSOLA', 
        descripcion: 'Love seat con dos asientos reclinables y una práctica consola central con portavasos y almacenamiento.', 
        precio: 14500.00, 
        moneda: 'MXN', 
        materiales: ['Tela tipo lino', 'Madera', 'Mecanismo de metal', 'Plástico'], 
        dimensiones: { alto: 100, ancho: 190, profundidad: 98, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/reclinable_generico_love.jpg', 
        stock: 12,
        oferta: 0,
        porcentajeOferta: 0
    },
    {
        id: 325, 
        sku: 'REC-GEN-SOFA3P',
        categoria: 'Salas',
        subcategoria: 'Reclinables',
        nombre: 'SOFA RECLINABLE DE 3 PLAZAS', 
        descripcion: 'Comodidad para toda la familia. Sofá de tres plazas donde los dos asientos de los extremos son reclinables.', 
        precio: 18999.00, 
        moneda: 'MXN', 
        materiales: ['Tela', 'Madera de pino', 'Mecanismo manual'], 
        dimensiones: { alto: 103, ancho: 210, profundidad: 98, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/reclinable_generico_sofa3p.jpg', 
        stock: 10,
        oferta: 0,
        porcentajeOferta: 0
    },
    {
        id: 326, 
        sku: 'REC-GEN-MASAJE',
        categoria: 'Salas',
        subcategoria: 'Reclinables',
        nombre: 'SILLON RECLINABLE CON MASAJE', 
        descripcion: 'La experiencia de relajación definitiva con masaje por vibración en 8 puntos y función de calefacción.', 
        precio: 13500.00, 
        moneda: 'MXN', 
        materiales: ['Piel sintética', 'Componentes electrónicos', 'Espuma'], 
        dimensiones: { alto: 108, ancho: 92, profundidad: 96, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/reclinable_generico_masaje.jpg', 
        stock: 9,
        oferta: 0,
        porcentajeOferta: 0
    },
    {
        id: 327, 
        sku: 'REC-GEN-MECEDORA',
        categoria: 'Salas',
        subcategoria: 'Reclinables',
        nombre: 'SILLON RECLINABLE TIPO MECEDORA', 
        descripcion: 'Doble función, doble confort. Además de reclinarse, tiene una suave función de mecedora.', 
        precio: 7999.00, 
        moneda: 'MXN', 
        materiales: ['Tela', 'Madera', 'Metal'], 
        dimensiones: { alto: 105, ancho: 98, profundidad: 100, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/reclinable_generico_mecedora.jpg', 
        stock: 17,
        oferta: 0,
        porcentajeOferta: 0
    },
    {
        id: 328, 
        sku: 'REC-GEN-POWER',
        categoria: 'Salas',
        subcategoria: 'Reclinables',
        nombre: 'SILLON RECLINABLE ELECTRICO POWER', 
        descripcion: 'Confort al alcance de un botón. Reclinable eléctrico con control de posiciones y puerto USB integrado.', 
        precio: 11999.00, 
        moneda: 'MXN', 
        materiales: ['Piel sintética', 'Motor eléctrico', 'Acero', 'Puerto USB'], 
        dimensiones: { alto: 102, ancho: 95, profundidad: 100, unidad: 'cm' }, 
        img: 'https://www.muebleriaespana.com/salas/reclinable_generico_power.jpg', 
        stock: 15,
        oferta: 0,
        porcentajeOferta: 0
    }
]