export const products = [
    {
        id: 201, 
        sku: 'REF-SAM-T400',
        categoria: 'Linea Blanca',
        subcategoria: 'Refrigeradores',
        nombre: 'Refrigerador Samsung Top Mount 14 pies', 
        descripcion: 'Refrigerador con tecnología Digital Inverter para ahorro de energía y despachador de agua.', 
        precio: 14999.00, 
        moneda: 'MXN', 
        materiales: ['Acero inoxidable', 'Plástico', 'Cristal templado'], 
        dimensiones: { alto: 171, ancho: 67, profundidad: 66, unidad: 'cm' }, 
        img: '../assets/catalogos/linea_blanca/refrimabe_1.png', 
        stock: 8,
    },
    {
        id: 202, 
        sku: 'EST-MAB-EM76',
        categoria: 'Linea Blanca',
        subcategoria: 'Estufas',
        nombre: 'Estufa Mabe de Piso 30 pulgadas', 
        descripcion: 'Estufa de 6 quemadores con encendido electrónico y cubierta de acero inoxidable. Horno de gran capacidad.', 
        precio: 9899.50, 
        moneda: 'MXN', 
        materiales: ['Acero inoxidable', 'Hierro fundido'], 
        dimensiones: { alto: 97, ancho: 76, profundidad: 70, unidad: 'cm' }, 
        img: '../assets/catalogos/linea_blanca/estufa_2.png', 
        stock: 15
    },
    {
        id: 203, 
        sku: 'LAV-WHP-CS22',
        categoria: 'Linea Blanca',
        subcategoria: 'Lavadoras',
        nombre: 'Lavadora Whirlpool Carga Superior 22 kg', 
        descripcion: 'Lavadora con sistema Xpert System para ciclos de lavado eficientes y tina de acero inoxidable.', 
        precio: 12500.00, 
        moneda: 'MXN', 
        materiales: ['Acero', 'Plástico reforzado'], 
        dimensiones: { alto: 111, ancho: 66, profundidad: 66, unidad: 'cm' }, 
        img: '../assets/catalogos/linea_blanca/lavadora_3.png', 
        stock: 10
    },
    {
        id: 204, 
        sku: 'MIC-LG-N32',
        categoria: 'Linea Blanca',
        subcategoria: 'Hornos de Microondas',
        nombre: 'Horno de Microondas LG NeoChef 1.5 pies³', 
        descripcion: 'Horno con tecnología Smart Inverter para una cocción uniforme y rápida. Acabado tipo espejo.', 
        precio: 3899.00, 
        moneda: 'MXN', 
        materiales: ['Acero', 'Cristal', 'Cerámica'], 
        dimensiones: { alto: 30, ancho: 54, profundidad: 42, unidad: 'cm' }, 
        img: '../assets/catalogos/linea_blanca/micro_4.png', 
        stock: 25
    },
    {
        id: 205, 
        sku: 'REF-LG-F25',
        categoria: 'Linea Blanca',
        subcategoria: 'Refrigeradores',
        nombre: 'Refrigerador LG French Door 25 pies³', 
        descripcion: 'Refrigerador de puerta francesa con dispensador de agua y hielo, y sistema Door-in-Door.', 
        precio: 34599.00, 
        moneda: 'MXN', 
        materiales: ['Acero inoxidable', 'Plástico'], 
        dimensiones: { alto: 179, ancho: 91, profundidad: 73, unidad: 'cm' }, 
        img: '../assets/catalogos/linea_blanca/refrifrench_5.png',
        stock: 5
    },
    {
        id: 206, 
        sku: 'SEC-MAY-G18',
        categoria: 'Linea Blanca',
        subcategoria: 'Secadoras',
        nombre: 'Secadora de Gas Maytag 18 kg', 
        descripcion: 'Secadora de alta capacidad con sensor de humedad para un secado óptimo y prevención de arrugas.', 
        precio: 11999.00, 
        moneda: 'MXN', 
        materiales: ['Acero', 'Aluminio'], 
        dimensiones: { alto: 109, ancho: 69, profundidad: 74, unidad: 'cm' }, 
        img: '../assets/catalogos/linea_blanca/secadora_6.png', 
        stock: 9
    },
    {
        id: 207, 
        sku: 'LAV-SAM-F20',
        categoria: 'Linea Blanca',
        subcategoria: 'Lavavajillas',
        nombre: 'Lavavajillas Samsung Acero Inox', 
        descripcion: 'Lavavajillas silencioso con tercer rack para cubiertos y sistema de secado StormWash.', 
        precio: 13999.00, 
        moneda: 'MXN', 
        materiales: ['Acero inoxidable'], 
        dimensiones: { alto: 85, ancho: 60, profundidad: 60, unidad: 'cm' }, 
        img: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&h=600&fit=crop', 
        stock: 11
    },
    {
        id: 208, 
        sku: 'EST-IO-P76',
        categoria: 'Linea Blanca',
        subcategoria: 'Parrillas',
        nombre: 'Parrilla de Gas IO Mabe 5 quemadores', 
        descripcion: 'Parrilla empotrable de cristal negro con 5 quemadores de distintos tamaños y arañas de hierro fundido.', 
        precio: 8300.00, 
        moneda: 'MXN', 
        materiales: ['Cristal templado', 'Hierro fundido'], 
        dimensiones: { alto: 10, ancho: 76, profundidad: 52, unidad: 'cm' }, 
        img: 'https://images.unsplash.com/photo-1600489000022-c2086d79f9d4?w=600&h=600&fit=crop', 
        stock: 18
    },
    {
        id: 209, 
        sku: 'CAM-TEK-D60',
        categoria: 'Linea Blanca',
        subcategoria: 'Campanas',
        nombre: 'Campana de Pared Teka Acero Inox 60cm', 
        descripcion: 'Campana extractora decorativa con 3 velocidades de extracción, filtros de aluminio y luz LED.', 
        precio: 4500.00, 
        moneda: 'MXN', 
        materiales: ['Acero inoxidable', 'Aluminio'], 
        dimensiones: { alto: 80, ancho: 60, profundidad: 50, unidad: 'cm' }, 
        img: 'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=600&h=600&fit=crop', 
        stock: 22
    },
    {
        id: 210, 
        sku: 'CON-HIS-V10',
        categoria: 'Linea Blanca',
        subcategoria: 'Congeladores',
        nombre: 'Congelador Horizontal Hisense 10 pies³', 
        descripcion: 'Congelador tipo cofre de gran capacidad, ideal para almacenar alimentos por largos periodos.', 
        precio: 7299.00, 
        moneda: 'MXN', 
        materiales: ['Acero', 'Plástico'], 
        dimensiones: { alto: 85, ancho: 112, profundidad: 63, unidad: 'cm' }, 
        img: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=600&h=600&fit=crop&sat=-100', 
        stock: 14
    }
];